### ISSUE TITLE
Schedule: start date

### ISSUE THREAD

**Issue by pistonsky** [sukazavr/ctrl.finance#3]
For periodic expenses, along with end date, there should be a way to set the start date as well.

**Comment by sukazavr** [comment]
Yeah! I think it's useful. I'll add this feature to my private roadmap. Thx.

**Comment by sukazavr** [comment]
Done https://github.com/sukazavr/ctrl.finance/commit/40c71321b429f4411cdcea99a8e66e84d47a4fb5
